const CLASSNAME = {
  WISHLIST: {
    WRAPPER: 'cart_Wrapper',
    TEXT: 'cart_text',
    IMAGE_SECTION: 'cart_imageSection',
  },

  ERROR_SECTION: {
    ERROR: 'error',
  },

  FILTER: {
    MAIN_SECTION_FILTER: 'sample-mainSectionFilter',
    FILTER_TITLE: 'sample-filterTitle',
    SUBCATEGORY: 'sample-subcategory',
    BRAND: 'sample-brand',
    PRICE: 'sample-price',
    SUBCATEGORY_LIST: 'sample-subcategoryOption',
    SUBCATEGORY_ITEM: 'sample-subcategoryOption__item',
    NO_PRODUCTS: 'sample-brandOption__noBrand',
    BRAND_LIST: 'sample-brandOption',
    BRAND_ITEMS: 'sample-brandOption__item',
    PRICE_LIST: 'sample-priceOption',
    PRICE_MIN: 'sample_priceMin',
    PRICE_MAX: 'sample_priceMax',
    APPLY: 'sample-priceOption__apply',
    ACTIVE: 'sample-active',
  },

  IMAGE_TRANSITION: {
    IMAGE_SECTION: 'imageSection',
    LOGIN_SLIDE_BUTTON: 'login_slide_button',
    LOGIN_SLIDE_PREV: 'login_slide_prev',
    LOGIN_SLIDE_NEXT: 'login_slide_next',
    LOGIN_DOTS_CONTAINER: 'login_dots_container',
    SLIDE: 'slide',
    ACTIVE: 'active',
    DOT: 'dot',
  },

  POST_COMMON: {
    LABEL: 'post-label',
    DETAIL_TEXT: 'postForm_detailText',
    WRAPPER: 'postFormWrapper',
    ERROR: 'textField_error',
    FUEL: 'postForm_FuelOption',
    LOCATION_WRAPPER: 'postForm_LocationWrapper',
    LOCATION_TEXT: 'postForm_LocationText',
    SELLER_WRAPPER: 'postForm_SellerWrapper',
    SELLER_TEXT: 'postForm_SellerText',
    POST: 'postForm_post',
    //   Description
    LABEL_WRAPPER: 'post-labelWrapper',
    DESCRIPTION: 'postForm_Description',
    INPUTERROR: 'postErrorInput',
    // Text Field
    CONTAINER: 'textField',
    INPUT: 'textField_input',
    // Photos Field
    UPLOAD_TEXT: 'postForm_UploadText',
    PHOTO_CONTAINER: 'postForm_photo-container',
    PHOTO_BOX: 'postForm_photo-box',
    PREVIEW: 'postForm_photo-preview',
    UPLOAD: 'postForm_photo-upload',
    FILE_INPUT: 'postForm_file-input',
    CAMERA: 'postForm_Camera',
    ADD_PHOT0: 'postForm_phototext',
    PREVIEW_WRAPPER: 'postForm_PreviewWrapper',
    // Price Field
    PRICE_WRAPPER: 'postForm_PriceWrapper',
    PRICE_TEXT: 'postForm_PriceText',
    PRICE: 'postForm_Price',
    PRICE_INPUT_WRAPPER: 'postForm_PriceInputWrapper',
    // Seller
    SELLER_VERIFY_TEXT: 'postForm_SellerVerifyText',
    SELLER_CODE_TEXT: 'postForm_SellerCodeText',
    MOBILE_NUMBER: 'postForm_MobileNumber',
    MOBILE_NUMBER_WRAPPER: 'postForm_mobileNumberWrapper',
    // State
    STATE_INPUT_WRAPPER: 'postForm_StateWrapper',
    STATE: 'postForm_State',
    STATE_LIST: 'postForm_StateList',
    STATE_ITEMS: 'postForm_StateItems',
    // City
    CITY: 'postForm_City',
    CITY_LIST: 'postForm_CityList',
  },

  LOADER: {
    LOADING: 'loading',
  },

  PAGINATION: {
    WRAPPER: 'sample-PageChange',
    PREV: 'sample-PREV',
    DISABLED: 'sample-disabled',
    PAGE_COUNT_WRAPPER: 'sample-pagewrapper',
    PAGE_NUMBER: 'sample-pageNumber',
    ACTIVE_PAGE: 'sample-activepage',
    NEXT: 'sample-NEXT',
  },

  SCHEMER: {
    COMMON: 'schemer_common',
    COMMON_BOX: 'schemer_common_box',
    COST: 'schemer_cost',
    DISTANCE: 'schemer_distance',
    NAME: 'schemer_name',
    PLACE_DATE_WRAPPER: 'schemer_placeAndDate_wrapper',
    PLACE: 'schemer_place',
    DATE: 'schemer_date',
  },

  PRODUCT_IMAGE: {
    WRAPPER: 'carImages_wrapper',
    IMAGE_WRAPPER: 'carImages',
    IMAGE: 'carImages_image',
    CART_WRAPPER: 'carImage_cart_Parent',
    CONTENT: 'carImages_content',
    COST: 'carImage_cost',
    DISTANCE: 'carImage_distance',
    NAME: 'carImage_name',
    PLACE_DATE_WRAPPER: 'carImage_placeAndDate',
    PLACE: 'carImage_place',
    DATE: 'carImage_date',
  },

  FIREBASE: {
    NO_USERS: 'no_users',
    CHAT_APP: 'chat-app',
    USER_WRAPPER: 'userWrapper',
    USER: 'user',
    USER_LIST: 'user-list',
    MESSAGE_WRAPPER: 'message-wrapper',
    MESSAGE_LIST: 'message-list',
    NO_MSG: 'no_message',
    MESSAGE_TEXT: 'message-text',
    MESSAGE_TIME: 'message-time',
    INPUT_WRAPPER: 'input-wrapper',
    MESSAGE_INPUT: 'message-input',
    SEND_BUTTON: 'send-btn',
    USER_ITEM: 'user-item',
    ACTIVE_USER: 'activeUser',
    MESSAGE_ITEM: 'message-item',
    SENT: 'sent',
    RECEIVED: 'received',
    TICK_STATUS: 'tick-status',
    SEEN: 'seen',
    MESSAGE: 'message',
    UNREAD: 'unreadcount',
  },

  EDIT_ADS: {
    DETAIL_TEXT: 'editForm_detailText',
    WRAPPER: 'editForm_Wrapper',
    MAIN: 'editForm_Main',
    LOCATION_WRAPPER: 'editForm_LocationWrapper',
    LOCATION_TEXT: 'editForm_LocationText',
    POST: 'editForm_post',
  },

  ITEM_SELECTOR: {
    INPUT: 'home_nav_input_objects_field',
    WRAPPER: 'home_nav_input_objects',
    SEARCH: 'home_nav_input_object_search',
    SEARCH_ICON: 'home_nav_input_objects_icon',
  },

  LOCATION: {
    IFRAMES: 'locationMap-iframes',
    CONTAINER: 'map-container-div',
    TEXT: 'detail-page-minor-title',
  },

  LOGIN_DROPDOWN: {
    PROFILE_DROPDOWN: 'profile-dropdown',
    DROPDOWN_MENU: 'dropdown-menu',
    PROFILE_SECTION: 'profile-section',
    PROFILE_HEADER: 'profile-header',
    PROFILE_INITIAL: 'profile-large-initial',
    PROFILE_INFO: 'profile-info',
    PROFILE_EDIT_PROFILE: 'edit-profile-button',
    PROFILE_MENU_ITEMS: 'menu-items',
    PROFILE_MENU_ITEM: 'menu-item',
  },

  MODAL: {
    TEXT: 'modal_text',
    WRAPPER: 'modal_wrapper',
    BUTTON: 'modal_button',
    YES: 'modal_yes',
    NO: 'modal_no',
    CONTENT: 'modal-content',
  },

  PRODUCT_DETAIL_IMG: {
    IMAGE_SECTION: 'imageDetailimageSection',
    IMAGE_SLIDE: 'imageDetailSlide',
    ACTIVE: 'imageDetailActive',
    BUTTON: 'imageDetailLogin_slide_button',
    PREV: 'imageDetailLogin_slide_prev',
    NEXT: 'imageDetailLogin_slide_next',
    DOTS_CONTAINER: 'imageDeatilLogin_dots_container',
    ACTIVE_IMAGES: 'ActiveImages',
    DOTS: 'imageDetailDot',
    ACTIVE_DOTS: 'imageDetailActive',
  },

  SELL_CATEGORY: {
    WRAPPER: 'sell-category',
    OPTIONS: 'sell-category__option',
  },

  SELL_SECTION: {
    WRAPPER: 'sell-section__category-container',
    SUBTITLE: 'sell-section__subtitle',
    CATEGORIES: 'sell-section__categories',
    CATEGORY: 'sell-section__category-wrapper',
    CATEGORY_BUTTON: 'sell-section__category-button',
    ACTIVE: 'sell-section_active',
    CATEGORY_ICON: 'sell-section__category-icon',
    CATEGORY_NAME: 'sell-section__category-name',
    ARROW: 'sell-section__arrow-icon',
    SUBCATEGORIES: 'sell-section__subcategories',
  },

  FOOTER: {
    WRAPPER: 'footerSectionParent',
    CHILD: 'footerSection',
    IMAGES_LIST: 'footerSectionChildImages',
    OLX: 'footerSectionOlx',
    CAR_TRADE_TECH: 'footerSectionCarTradeTech',
    CARWALE: 'footerSectionCarCarwale',
    IMAGES: 'footerSectionImages',
    CAR_TRADE: 'footerSectionCarTrade',
    BIKEWALE: 'footerSectionBikewale',
    SECTION_TEXT: 'footerSectionText',
    MOBILITY_OUTLOOK: 'footerSectionMobilityOutlook',
    ALL_RIGHT_RESERVED: 'footerSectionAllRightsReserved',
    SECTION_HELP: 'footerSectionHelp',
  },

  NAVBAR: {
    NAV_PARENT: 'home_nav_wrapper',
    LOGO: 'home_nav_logo',
    PLACE_WRAPPER: 'home_nav_place_wrapper',
    LANGUAGE_WRAPPER: 'home_nav_languageWrapper',
    CART_LOGIN_SELL: 'home_nav_cart_login_sell',
    CART: 'home_nav_cart',
    CART_ICON: 'home_nav_cart_icon',
    CHAT: 'home_nav_chat',
    NOTIFICATION: 'home_nav_notification',
    PROFILE: 'home_nav_profile',
    PROFILE_PHOTO: 'home_nav_profilephoto',
    PROFILE_INITIAL: 'home_nav-large-initial',
    PROFILE_UPDOWN: 'home_nav_profile_upDown',
    LOGIN: 'home_nav_login',
    SELL: 'home_nav_sell',
    SELL_ICON: 'home_nav_sell_icon',
    SELL_INNER: 'home_nav_sell_inner',
    SELL_ADD: 'home_nav_sell_add',
    SELL_TEXT: 'home_nav_sell_text',
    WISHLIST_WRAPPER: 'navWishlistWrapper',
    NAV: 'home_nav',
  },

  NAVCATEGORY: {
    CHILD: 'homeCategorychild',
    ALL_CATEGORY: 'home_navCategory_allCategory_Parent',
    ALL_CATEGORY_TEXT: 'home_navCategory_child_allCategory',
    CARS: 'home_navCategory_Cars',
    MOTORCYCLE: 'home_navCategory_Motorcycle',
    MOBILEPHONE: 'home_navCategory_MobilePhone',
    COMMERCIAL: 'home_navCategory_Commercial',
    LIST: 'home_navCategory_childs',
    WRAPPER: 'home_navCategory',
  },

  PROMOTED_CONTENT: {
    CONTENT: 'adsSection_Content',
    CONTAINER: 'adsSection_ContentContainer',
    LABEL: 'adsSection_ContentLabel',
    IMAGE: 'adsSection_ContentImage',
    VIDEO: 'adsSection_ContentVideo',
    WRAPPER: 'adsSection_Wrapper',
  },

  SAMPLE: {
    ADD_SECTION: 'sample-addSection',
    TEXT_SECTION: 'sample-textSection',
    MAIN_SECTION_WRAPPER: 'sample-mainSectionWrapper',
    MAIN_SECTION_IMAGE: 'sample-mainSectionImage',
    MAIN_IMAGE_SECTION_WRAPPER: 'sample-mainImageSectionWrapper',
    SELECTED_OPTION: 'sample-selectedOptions',
    SELECTED_OPTION_WRAPPER: 'sample-selectedWrapper',
    SELECTED_OPTION_TEXT: 'sample-selectedText',
    SELECTED_OPTION_CROSS: 'sample-selectedCross',
    NO_PRODUCTS: 'sample-noProduct',
    WRAPPER: 'sample-Wrapper',
  },

  USERS_ADS: {
    TITLE: 'myads-title',
    AD_WRAPPER: 'myads-ad-wrapper',
    NO_ADS: 'myads-no-ads',
    ERROR: 'myads-error',
    LOADING: 'myads-loading',
    WRAPPER: 'myads-wrapper',
  },
  TYPE_SECTION: {
    WRAPPER: 'carWrapper',
  },
  SELL: {
    HEADER: 'sell-section__header',
    BACK_BUTTON: 'sell-section__back-button',
    TITLE: 'sell-section__title',
    OUTLET: 'sell-section-Outlet',
    FOOTER: 'sell-section-footer',
    WRAPPER: 'sell-section',
  },
  PROFILE: {
    PROFILE_TEXT_WRAPPER: 'profile-section-profile-text-wrapper',
    CROSS: 'profile-section-cross',
    EDIT: 'profile-section-edit',
    PROFILE_TEXT: 'profile-section-profile-text',
    CONTENT: 'profile-section-content',
    PROFILE_INITIAL: 'profile-section-profile-initial',
    USERNAME: 'profile-section-username',
    EMAIL: 'profile-section-email',
    PHONE: 'profile-section-phone',
    BIO: 'profile-section-bio',
    ADS: 'profile-section-adds',
    ADS_TEXT: 'profile-section-adds-text',
    ADS_COUNT: 'profile-section-adds-count',
    WRAPPER: 'profile-section-wrapper',
  },

  PRODUCT_DETAIL: {
    IMAGE_DETAIL_DESCRIPTION: 'imageDetailImagesDetailsDescription',
    IMAGE: 'imageDetailImageSection',
    DETAIL_DESCRIPTION: 'imageDetailDetailsDescription',
    DETAIL: 'imageDetailDetails',
    DETAIL_TEXT: 'imageDetailTitle',
    BRAND: 'imageDetailBrand',
    BRAND_TEXT: 'imageDetailBrandTitle',
    BRAND_VALUE: 'imageDetailBrandValue',
    DESCRIPTION: 'imageDetailDescription',
    DESCRITION_VALUE: 'imageDetailDescriptionValue',
    DESCRIPTION_TITLE: 'imageDetailDescriptionTitle',
    PRICE_CHAT_WRAPPER: 'imageDetailPriceChatSection',
    PRICE: 'imageDetailPriceSection',
    PRICE_VALUE: 'imageDetailPriceValue',
    PRICE_TEXT: 'imageDetailPriceName',
    PRICE_PLACE: 'imageDetailPricePlace',
    PRICE_TAG: 'imageDetailPriceTags',
    PRICE_DATE: 'imageDetailPriceDate',
    CHAT: 'imageDetailChatSection',
    CHAT_TEXT_PHOTO: 'imageDetailChatSellerPhotoText',
    CHAT_PHOTO: 'imageDetailChatSeller',
    CHAT_TEXT: 'imageDetailChatText',
    CHAT_UPDOWN: 'imageDetailChatUpdown',
    CHAT_BUTTON: 'imageDetailChat',
    POST: 'imageDetailPost',
    POST_TEXT: 'imageDetailPostText',
    POST_VALUE: 'imageDetailPostValue',
    MAP: 'imageDetailMap',
    WRAPPER: 'imageDetailWrapper',
  },
  DASHBOARD: {
    IMAGE_SECTION: 'homeImageSection',
    LOAD: 'homeLoadMore',
    NO_PRODUCTS: 'homeNoProducts',
    LOADER: 'loader',
    WRAPPER: 'homeImageSectionWraper',
  },
  EDIT_PROFILE: {
    HEADER_WRAPPER: 'edit-profile-header-wrapper',
    EDIT_TEXT: 'edit-profile-text',
    POST: 'edit-profile-edit',
    CROSS: 'edit-profile-cross',
    VIEW_PROFILE: 'edit-profile-view-profile',
    WRAPPER: 'edit-profile-wrapper',
  },
  HOME: {
    OUTLET: 'AppOutlet',
    WRAPPER: 'AppWrapper',
  },

  POST_FORM: {
    SELECTED_CATEGORY: 'postSelectedCategory',
    SELECTED_CATEGORY_TITLE: 'postSelectedCategoryTitle',
    SELECTED_CATEGORY_NAME: 'postSelectedCategoryName',
    POST_DETAIL: 'postSellerDetail',
    WRAPPER: 'post-wrapper',
  },

  VERIFICATION: {
    TEXT_WRAPPER: 'verification_login_section',
    LOGIN: 'verification_login_button',
    TEXT: 'verification_login_text',
    EMAIL: 'verification_email_text',
    WRAPPER: 'verification_wrapper',
  },

  SIGNUP: {
    HEADER: 'signup_Header',
    CROSS: 'signup_Cross',
    BACK: 'signup_Back',
    TITLE: 'signup_title',
    USERNAME_INPUT: 'signup_usernameInput',
    EMAIL_INPUT: 'signup_emailInput',
    PASSWORD_INPUT: 'signup_passwordInput',
    CONFIRM_PASSWORD_INPUT: 'signup_confirmPasswordInput',
    SUBMIT_BUTTON: 'signup_submitButton',
    ERROR: 'signup_error',
    SIGNIN: 'signup_signin',
    REQUIRED: 'signup_required',
    EYE: 'signup_isSeenPassword',
    INPUT_PASSWORD_WRAPPER: 'signup_passwordWrapper',
    WRAPPER: 'signup_Wrapper',
  },

  SIGNIN: {
    HEADER: 'signin_header',
    CROSS: 'signin_cross',
    BACK: 'signin_back',
    TITLE: 'signin_title',
    EMAIL_INPUT: 'signin_emailInput',
    PASSWORD_INPUT: 'signin_passwordInput',
    SUBMIT_BUTTON: 'signin_submitButton',
    ERROR: 'signin_error',
    FORGET: 'signin_forgetpass',
    SINUP: 'signin_signup',
    REQUIRED: 'signin_required',
    EYE: 'signin_isSeenPassword',
    INPUT_PASSWORD_WRAPPER: 'signin_passwordWrapper',
    WRAPPER: 'signin_Wrapper',
  },

  NEW_PASSWORD: {
    TITLE: 'newpass_title',
    PASSWORD_INPUT: 'newpass_passwordInput',
    CONFIRM_PASSWORD_INPUT: 'newpass_confirmPasswordInput',
    SUBMIT_BUTTON: 'newpass_submitButton',
    EMAIL_INPUT: 'newpass_emailInput',
    ERROR: 'newpass_error',
    SUCCESS: 'newpass_success',
    SUCCESS_TEXT: 'newpass_sucessText',
    SUCCESS_LOGIN: 'newpass_sucessLogin',
    REQUIRED: 'newpass_required',
    EYE: 'newpass_isSeenPassword',
    INPUT_PASSWORD_WRAPPER: 'newpass_passwordWrapper',
    WRAPPER: 'newpass_Wrapper',
  },

  LOGIN_SECTION: {
    SECTION: 'loginPageChild',
    GOOGLE_WRAPPER: 'continue_with_google_parent',
    GOOGLE_ICON: 'continue_with_google_icon',
    GOOGLE_TEXT: 'continue_with_google_text',
    OR: 'login_Or_section',
    SIGNUP: 'login_signup',
    SIGNIN: 'login_signin',
    SIGNIN_TEXT: 'login_signin_link',
    FOOTER: 'login_footer_parent',
    FOOTER_UPPER_TEXT: 'login_footer_first_section',
    FOOTER_SECOND_TEXT: 'login_footer_second_section',
    WRAPPER: 'loginPageParent',
  },

  FORGOT_PASS: {
    HEADER: 'forget_Header',
    CROSS: 'forget_Cross',
    BACK: 'forget_Back',
    TITLE: 'forget_title',
    EMAIL_INPUT: 'forget_emailInput',
    TEXT: 'forget_text',
    SUBMIT_BUTTON: 'forget_submitButton',
    ERROR: 'forget_error',
    REQUIRED: 'forget_required',
    WRAPPER: 'forget_Wrapper',
  },

  USERS_ADS_IMG: {
    IMAGE: 'myadsImages_images',
    CONTENT: 'myadsImages_content',
    COST: 'myadsImages_cost',
    STATUS: 'myadsImages_STATUS',
    DATE: 'myadsImages_date',
    LOCATION: 'myadsImages_location',
    NAME: 'myadsImages_name',
    PLACE_DATE: 'myadsImages_place_date',
    EDIT_DELETE: 'myadsImages_edit_delete',
    EDIT: 'myadsImages_edit',
    DELETE: 'myadsImages_delete',
    WRAPPER: 'myadsImages_wrapper',
  },
};

export default CLASSNAME;
