import { SUBCATEGORIES } from '../Components/CustomComponents/SellCategory/constant';

export const COMMON_TEXT = {
  IMG: 'img',
  BUTTON: 'button',
  NUMBER: 'number',
  ERROR_IN_LOADING_PRODUCTS: 'Error in loading products',
  LOADING: 'Loading products...',
  NO_PRODUCTS:
    'No items found for your current search. Let’s try something else!',
  SENDING: 'Sending...',
  EMAIL: 'Email',
  EMAIL_S: 'email',
  PASSWORD: 'Password',
  PASSWORD_S: 'password',
  TEXT: 'text',
  SUBMIT: 'submit',
  CONFIRM_PASSWORD_S: 'confirmPassword',
  LOGIN_TO_CHAT: 'Ready to chat? Log in to get started',
  DAYS_AGO: 'days ago',
  NO_WISHLIST:
    'No items saved yet. When you find something you love, click the heart icon to add it here.',
  EDITING: 'Editing...',
  SOMETHING_WENT_WRONG: 'Something went wrong',
  CATEGORY: 'Category',
  NO_CATEGORY: 'No category available',
  NO_BRAND: 'No brand available',
  BRAND: 'Brand',
  PRICE: 'Price',
  PRICE_MIN: 'Min',
  PRICE_MAX: 'Max',
  APPLY: 'Apply',
  SLIDE_BUTTON: 'loginSlideButton',
  DOTS: 'loginDots',
  GO_TO_SLIDE: 'Go to slide',
  LOGIN_IMAGES: 'loginImages',
  NEXT: 'Next',
  PREV: 'Prev',
  PAGE: 'page',
  ADD_TO_WISHLIST: 'Add to Wishlist',
  WISHLIST: 'WISHLIST',
  INCLUDE_DETAIL: 'INCLUDE SOME DETAILS',
  CONFIRM_LOCATION: 'CONFIRM YOUR LOCATION',
  EDIT: 'Edit',
  REVIEW_DETAIL: 'REVIEW YOUR DETAILS',
  SUCCESS_IN_EDITING: 'ADs edited successfully',
  ERROR_IN_EDITING: 'Error in editing',
  LOGIN_TO_ADD_TO_WISHLIST: 'Please login to add to wishlist',
  ERROR_IN_ADDING: 'Error adding to wishlist',
  ADDED_IN_FAV: 'Added in Favourites',
  ADDED: 'Added',
  ADDED_IN_WISHLIST: 'Added to your wishlist!',
  REMOVE_FROM_WISHLIST: 'Removed from your wishlist.',
  DELETE: 'Delete',
  DELETE_TEXT: 'Are you sure you want to delete this ad?',
  EDIT_TEXT: 'Are you sure you want to edit this ad?',
  SUCCESS: 'Ad deleted successfully',
  ERROR_IN_DELETING: 'Error while deleting ad',
  FINDS_CARS_MOBILE_AND_MORE: 'Find Cars, Mobile Phones and more',
  LOADING_MAPS: 'Loading map...',
  VIEW_AND_EDIT_PROFILE: ' View and Edit Profile',
  SIGNOUT: 'Sign Out',
  ERROR_SIGNOUT: 'Error occurs in Sign Out',
  SIGN_OUT_SUCCESSFULLY: 'Sign Out successfully',
  ARE_YOU_SURE: 'Are you sure you want to Sign Out?',
  YES: 'Yes',
  NO: 'No',
  VERIFY: "Let's verify your account",
  CONFIRMATION:
    ' We will send you a confirmation code by sms on the next step.',
  CODE: '+91',
  UPLOAD_PHOTOS: 'UPLOAD UP TO 5 PHOTOS',
  ADD_PHOTO: 'Add Photo',
  POSTED_SUCCESSFULLY: 'Post Successfuly!',
  ERROR: 'Error',
  ERROR_IN_POSTING: 'Error in posting',
  POST: 'POST',
  SELECT_THIS_CATEGORY: 'Select this category',
  CHOOSE_YOUR_CATEGORY: 'Choose Your Category',
  HELP_SITEMAP: 'Help-Sitemap',
  ALL_RIGHT_RESERVED: 'All rights reserved © 2006-2025 OLX',
  LOGIN: 'Login',
  SELL: 'SELL',
  SIGNIN_TO_ACCESS_WISHLIST: 'Sign in to view your wishlist',
  SIGNIN_TO_ADD_PRODUCT: 'Sign in to start listing your product',
  ALL_CATEGORIES: 'ALL CATEGORIES',
  MULTI_WHEEL_VEHICLE: 'Multi Wheel Vehicles',
  BIKES: 'Bikes',
  MOBILE_PHONE: 'Mobile Phone',
  ELECTRONICS: 'Electronics',
  PROMOTED_CONTENT: 'Promoted Content',
  VIDEO_CONTENT: 'Video content',
  NO_PRODUCT_AVAILABLE:
    'Oops! This shelf is empty for now. Why not explore our other collections while we restock?',
  CHECK_YOUR_EMAIL: 'CHECK YOUR EMAIL',
  FORGOT_PASSWORD: 'Forgot Password',
  PLEASE_ENTER_YOUR_EMAIL:
    'Please enter your email address and we will send you a link to reset your password.',
  SEND_RESET_LINK: 'Send Reset Link',
  PLEASE_ENTER_VALID_EMAIL: 'Please enter a valid email address',
  CHECK_YOUR_INBOX: 'Check your Email',
  SOMETHING_WENT_WRONG_TRY_AGAIN: 'Something went wrong, please try again',
  CONTINUE_WITH_GOOGLE: 'Continue with Google',
  SIGN_UP_WITH_EMAIL: 'Signup with Email',
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
  PERSONAL_DETAIL: 'All your personal details are safe with us',
  PRIVACY_POLICY:
    'If you continue, you are accepting OLX Terms and Conditions and Privacy Policy',
  CONFIRM_PASSWORD: 'Confirm Password',
  NEW_PASSWORD: 'New Password',
  FORGET_PASWORD: 'Forgot Password',
  SET: 'Set',
  PASSWORD_CHANGED:
    '🔐  Your password has been changed. Please sign in again to continue.',
  SIGN_IN: 'Sign In',
  ERROR_IN_CHANGING_PASSWORD: 'Error in changing password',
  PASSWORD_CHANGED_SUCCESSFULLY: 'Password Changed Successfully',
  LOGIN_SUCCESSFUL: 'Login Successfull',
  DONOT_HAVE_ACCOUNT: "Don't have an account ?",
  SIGN_UP: 'Sign Up',
  USERNAME: 'Username',
  USERNAME_S: 'username',
  SIGNUP_SUCCESSFULLY: 'Signup Successfully',
  HAVE_ACCOUNT: 'Already have an account ?',
  VERIFICATION_TEXT:
    'we sent you a verification link to your email, please check your inbox.',
  AFTER_VERIFICATION: 'After Verification',
  LOAD_MORE: 'Load More',
  EDIT_PROFILE: 'Edit Profile',
  SUBMIT_BUTTON: 'Save Changes',
  VIEW_PROFILE: 'View Profile',
  PROFILE_UPDATED_SUCCESSFULLY: 'Profile updated successfully',
  ERROR_UPDATING_PROFILE: 'Error updating profile',
  SEND: 'Send',
  MESSAGES: 'Messages',
  USER: 'User',
  TYPE_MESSAGE: 'Type a message',
  NO_MSG:
    'No messages yet. Say hello to start the conversation!  Select a seller roomId to message and unlock better deals, faster responses, and secure transactions!',
  NO_CONVERSATIONS:
    'No conversations yet. Start chatting by connecting with seller!',
  SELECT_SELLER_ROOMID:
    'Select a seller roomId to message and unlock better deals, faster responses, and secure transactions!',
  ERROR_SENDING_MESSAGE: 'Error sending message. Please try again later.',
  SESSION_EXPIRED: '!! Session Expired, Please Login Again',
  SELECTED_CATEGORY: 'SELECTED CATEGORY',
  DETAIL: 'Details',
  TITLE: 'Title',
  DESCRIPTION: 'Description',
  PRODUCT: 'Product',
  OLX_INDIA: 'OLX India',
  CHAT_WITH_SELLER: 'Chat with Seller',
  POSTED_IN: 'Posted in',
  CHAT: 'chat',
  PROFILE: 'Profile',
  MYADS: 'my ads',
  POST_YOUR_AD: 'Post your Ad',
  BACK: 'back',
  NO_ADS:
    'Ready to sell something? List your first product and start reaching buyers today! ',
  MY_ADS: 'My Ads',
  CLICK: 'click',
  GO_TO_HOME: 'Go to Home',
  POSTING: 'Posting...',
  SUBCATEGORY: 'Subcategory',
  PURCHASE_IN: 'Purchase in',
};

// inputTypes.ts
export const TYPE = {
  EMAIL: 'email',
  PASSWORD: 'password',
  TEXT: 'text',
  SUBMIT: 'submit',
  BUTTON: 'button',
  NUMBER: 'number',
} as const;
