export const carTradeTech =
  'https://statics.olx.in/external/base/img/cartrade/logo/cartrade_tech.svg?v=1';
export const carWale =
  'https://statics.olx.in/external/base/img/cartrade/logo/carwale.svg?v=1';
export const bikeWale =
  'https://statics.olx.in/external/base/img/cartrade/logo/bikewale.svg?v=1';
export const carTrade =
  'https://statics.olx.in/external/base/img/cartrade/logo/cartrade.svg?v=1';
export const mobilityOutlook =
  'https://statics.olx.in/external/base/img/cartrade/logo/mobility.svg?v=1';
export const OlxWhite =
  'https://statics.olx.in/external/base/img/cartrade/logo/olx.svg?v=1';
